apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - platform-marker.yaml

  - ../../../bootstrap/crossplane/providers/provider-kubernetes.yaml
  - ../../../bootstrap/crossplane/providers/providerconfig-incluster.yaml

  - ../../../bootstrap/crossplane/contract/xrd-postgresinstance.yaml
  - ../../../bootstrap/crossplane/contract/xrd-redisinstance.yaml

  - ../../../bootstrap/crossplane/contract/composition-dev-postgres.yaml
  - ../../../bootstrap/crossplane/contract/composition-dev-redis.yaml
