apiVersion: idp.platform.io/v1alpha1
kind: RedisInstance
metadata:
  name: xxxxx-1-redis
  namespace: apps-dev
  labels:
    idp.platform.io/app: xxxxx-1
    idp.platform.io/env: "dev"
    idp.platform.io/owner: "group:default/boxoffice"
spec:
  plan: dev
