apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-41-del
  title: python-app-41-del
  description: python-app-41-del testes
  annotations:
    idp.platform.io/state-repo: "github.com?owner=clecioantao&repo=platform-state-repo"
    idp.platform.io/app-path-dev: "apps/dev/python-app-41-del"
    idp.platform.io/app-path-prod: "apps/prod/python-app-41-del"
spec:
  type: service
  lifecycle: experimental
  owner: group:default/backstage
