apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - platform-marker.yaml
  # Step 2 vai adicionar: Crossplane contract (XRD/Compositions) e política PROD (bloqueado)

