apiVersion: idp.platform.io/v1alpha1
kind: PostgresInstance
metadata:
  name: app1-postgres
  namespace: apps-dev
spec:
  compositionSelector:
    matchLabels:
      idp.platform.io/provider: kubernetes
      idp.platform.io/env: dev

  parameters:
    app: app1
    env: dev
    owner: clecio
    size: small

  writeConnectionSecretToRef:
    name: app1-postgres-conn
