apiVersion: idp.platform.io/v1alpha1
kind: RedisInstance
metadata:
  name: app1-redis
  namespace: apps-prod
spec:
  compositionSelector:
    matchLabels:
      idp.platform.io/provider: kubernetes
      idp.platform.io/env: prod

  parameters:
    app: app1
    env: prod
    owner: clecio
    size: small

  writeConnectionSecretToRef:
    name: app1-redis-conn
