apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: platform-templates
spec:
  type: file
  targets:
    - ../templates/flask-app-standard/template.yaml
    - ../templates/attach-postgres/template.yaml
    - ../templates/attach-redis/template.yaml
